######################################################################
# Automatically generated by qmake (2.01a) ?t 8 27 22:28:54 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += link_pkgconfig
PKGCONFIG += gstreamer-0.10
PKGCONFIG += gstreamer-interfaces-0.10

# Input
HEADERS += gstexception.h gstinput.h qspectrum.h
SOURCES += gstinput.cpp main.cpp qspectrum.cpp
