######################################################################
# Automatically generated by qmake (2.01a) ne 3 14 23:40:55 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qlisttest.h
SOURCES += qlisttest.cpp
